### ISSUE TITLE
Error: object 'population' not found

### ISSUE THREAD

**Issue by Siddhant** [sourish-cmi/Covid19#1]
Reference line:
https://github.com/sourish-cmi/Covid19/blob/981f628abea418989fe1393c5099179ae7a3fb86/state_wise_R0_estimation.R#L51

I can't see where the 'population' object is being created.

**Comment by sourish-cmi** [comment]
Updated the code with population size:

### Population data
nms<-c("China","India","US","Iran","SouthKorea","Japan","Italy","France","Germany","Spain")

population<-c(1401754280,1359772087,329448153,83279228,51780579,126010000,60243406,67064000,83149300,47100396)

names(population)<-nms

**Comment by Siddhant** [comment]
Works now. Thanks.
