### ISSUE TITLE
Loop iterator does not loop; is fixed to 'Punjab' (i=24)

### ISSUE THREAD

**Issue by Siddhant** [sourish-cmi/Covid19#2]
https://github.com/sourish-cmi/Covid19/blob/981f628abea418989fe1393c5099179ae7a3fb86/state_wise_R0_estimation.R#L316

**Comment by sourish-cmi** [comment]
Yes - it is a bug. I will update immediately.


Sourish
Associate Professor
Chennai Mathematical Institute, INDIA
https://www.cmi.ac.in/~sourish/

**Comment by sourish-cmi** [comment]
Updated
